package com.ahndwon.sectionrecyclerviewexample

import com.ahndwon.sectionrecyclerviewexample.items.*

object Dummies {
//    val items = arrayListOf(
//        HeaderOne("HEADER - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 2"),
//        ChildOne("this is body - 3"),
//        ChildOne("this is body - 4"),
//        HeaderTwo("HEADER - 2"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 1"),
//        HeaderOne("HEADER - 3"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 2"),
//        ChildOne("this is body - 3"),
//        ChildOne("this is body - 3"),
//        HeaderTwo("HEADER - 4"),
//        ChildTwo("this is body - 1"),
//        ChildTwo("this is body - 2"),
//        ChildTwo("this is body - 3"),
//        ChildTwo("this is body - 4"),
//        ChildTwo("this is body - 4"),
//        ChildTwo("this is body - 4"),
//        HeaderOne("HEADER - 5"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1"),
//        ChildOne("this is body - 1")
//    )

    val items = arrayListOf(
        HeaderOne("HEADER - 1"),
        ChildOne(ListItem("1", "test")),
        ChildOne(ListItem("1", "test")),
        ChildOne(ListItem("1", "test")),
        ChildOne(ListItem("1", "test")),
        HeaderTwo("HEADER - 2"),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        ChildTwo(ListItem("2", "test2")),
        HeaderOne("HEADER - 3"),
        ChildOne(ListItem("3", "test")),
        ChildOne(ListItem("3", "test")),
        ChildOne(ListItem("3", "test")),
        ChildOne(ListItem("3", "test")),
        ChildOne(ListItem("3", "test")),
        HeaderTwo("HEADER - 4"),
        ChildTwo(ListItem("4", "test")),
        ChildTwo(ListItem("4", "test")),
        ChildTwo(ListItem("4", "test")),
        ChildTwo(ListItem("4", "test")),
        ChildTwo(ListItem("4", "test")),
        HeaderOne("HEADER - 5"),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test")),
        ChildOne(ListItem("5", "test"))

        )
}